Dev user endpoint
fedora-infra/webhook-to-fedora-messaging pull request #25
Opened 2024-07-02 10:13 UTC by brngylni

This PR adds the User endpoint #5

2024-07-08 04:20 UTC, gridhead requested changes
Also, please follow https://github.com/fedora-infra/webhook-to-fedora-messaging/pull/2#issuecomment-2134623677.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +
Please leave two lines of difference between each segregated block definition.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +        Used for creating a new user by sending a post request to /user/ path.
Get rid of the added tab please.

```suggestion
    Used for creating a new user by sending a post request to /user/ path.
```

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +    user, created = get_or_create(session, User, username=request.json['username'])
Add exception handling for `KeyError` (when the `username` key is not found in the JSON body). Abort the request with the `HTTP 429 Unprocessable Entity` error.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +
Use this empty line ;-)

If docstrings are created for a function of a kind, please ensure that they are created for other functions of that kind.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +    users = session.query(User).filter(User.username.like(request.json['username'])).all()
Add exception handling for `KeyError` (when the `username` key is not found in the JSON body). Abort the request with the `HTTP 429 Unprocessable Entity` error.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +    user = session.query(User).filter(User.username == request.json['username']).first()
Add exception handling for `KeyError` (when the `username` key is not found in the JSON body). Abort the request with the `HTTP 429 Unprocessable Entity` error.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +
More than two lines are left empty before the function definition.

Just two lines should be enough.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +def lookup_user():
If docstrings are created for a function of a kind, please ensure that they are created for other functions of that kind.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +from ..models.user import User
Ref. https://github.com/fedora-infra/webhook-to-fedora-messaging/pull/24#discussion_r1667901072

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +
Leave one empty line at the end of the file.

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +    return True
Maybe convert this to a decorator?

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/main.py
> +from .endpoints.user import user_endpoint
Ref. https://github.com/fedora-infra/webhook-to-fedora-messaging/pull/24#discussion_r1667901072

2024-07-08 04:20 UTC, gridhead commented on webhook_to_fedora_messaging/main.py
> +
Leave the line empty.

```suggestion

```

2024-07-10 05:08 UTC, gridhead requested changes
Please use the emojis to acknowledge the changes made and leave it for the reviewer to decide if the requested change has been made or not.

Once you are done with making the remaining changes - please squash the commits into one and then, it should be ready for a merge.

2024-07-10 05:08 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/user.py
> +
Please leave two lines of difference between each segregated block definition.

2024-07-10 05:08 UTC, gridhead commented on webhook_to_fedora_messaging/endpoints/util.py
> +
Please leave two lines of difference between each segregated block definition.

2024-07-11 04:49 UTC, gridhead requested changes
LGTM

@brngylni, please resolve the merge conflict and squash all commits into one.

2024-07-11 13:45 UTC, brngylni commented
> LGTM
> 
> @brngylni, please resolve the merge conflict and squash all commits into one.

Done!

2024-07-15 02:53 UTC, gridhead approved these changes
I am not dragging this any longer than it has to be. Other required changes can be made to the codebase after it is merged.

Merging now.

2024-07-15 02:53 UTC, merged